### ISSUE TITLE
Add `?? :: Buildable x => x -> Text`

### ISSUE THREAD

**Issue by gromakovsky** [aelve/fmt#22]
I propose to add a function with type `Buildable x => x -> Text`. 
Like `show`, but using `Buildable` instead of `Show` (and returning `Text` instead of `String`).
It's useful when you want to pretty print a single value of a type which is instance of `Buildable`.

**Comment by neongreen** [comment]
It's "fmt (build x)". I'm not sure it makes sense to create a new function
for this, but it's not a big deal so I can add it anyway. Do you have any
naming suggestions?

**Comment by neongreen** [comment]
I'm not doing much coding at the moment (outside of $dayjob where we don't use fmt), so this won't happen unless somebody thinks of a name and makes a PR.

I guess I'm okay with pretty. It's a sufficiently cheeky name.

**Comment by neongreen** [comment]
Okay, I finally got around to it. Expect a release in an hour or so.

**Comment by neongreen** [comment]
Well, or whenever Github gets less sick.

**Comment by neongreen** [comment]
@gromakovsky Released fmt-0.6.1 to Hackage.

**Comment by gromakovsky** [comment]
Thank you!
